// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func InjectConfig() (*Config, error) {
	config, err := Load()
	if err != nil {
		return nil, err
	}
	return config, nil
}

// wire.go:

var ProviderSet = wire.NewSet(Load)
