// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package terraform

import (
	"github.com/wbreza/wire-sample/pkg/exec"
	"github.com/wbreza/wire-sample/pkg/provisioning"
)

// Injectors from wire.go:

func InjectTerraformProvider(args ...any) (provisioning.Provider, error) {
	commandRunner := exec.NewShellCommandRunner()
	cli := NewCli(commandRunner)
	provider := NewTerraformProvider(cli)
	return provider, nil
}

// wire.go:

func Register() {
	provisioning.Register("terraform", InjectTerraformProvider)
}
