// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package actions

import (
	"github.com/wbreza/wire-sample/pkg/config"
	"github.com/wbreza/wire-sample/pkg/provisioning"
	"github.com/wbreza/wire-sample/pkg/tools/az"
)

// Injectors from wire.go:

func ProvideInitAction(template string) (Action, error) {
	cli := az.NewCli()
	action := NewInitAction(template, cli)
	return action, nil
}

func ProvideDeployAction() (Action, error) {
	cli := az.NewCli()
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	action := NewDeployAction(cli, configConfig)
	return action, nil
}

func ProvideProvisionAction(providerName string, args ...any) (Action, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	provider, err := provisioning.NewProvider(configConfig, providerName, args...)
	if err != nil {
		return nil, err
	}
	action := NewProvisionAction(provider)
	return action, nil
}
